[[server]]
name = "s.apsak-ng.org"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://s.apsak-ng.org"

[[server]]
name = "ng3.apsak.net"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng3.apsak.net"

[[server]]
name = "ng4.apsak.net"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng4.apsak.net"