[[server]]
name = "ng1.apsak.org"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng1.apsak.org"

[[server]]
name = "ng2.apsak.org"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng2.apsak.org"

[[server]]
name = "ng3.apsak.net"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng3.apsak.net"

[[server]]
name = "ng4.apsak.net"
location = "EU"
protocol = "borsh"
network = "mainnet"
address = "wss://ng4.apsak.net"